apiVersion: batch/v1
kind: CronJob
metadata:
  name: degewobot
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dagewobot-pv-claim
            persistentVolumeClaim:
              claimName: dagewobot-pv-claim
          containers:
          - name: degewobot-cronjob
            image: europe-west3-docker.pkg.dev/degewobot/images/degewobot:latest
            imagePullPolicy: Always
            command: [ "python" ]
            args: [ "main.py" ]
            volumeMounts:
            - name: dagewobot-pv-claim
              mountPath: /degewobot/data
            resources:
              limits:
                cpu: 1
                memory: 256Mi
              requests:
                cpu: 200m
                memory: 128Mi
          restartPolicy: Never
