  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dagewobot-pv-claim
    labels:
      app: dagewobot
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200M